% lorenz - Lorenz Attractor
%
% Lorenz, E.N., 1963
%
% Adapted for use with simEngine
% Copyright 2009-2010 Simatra Modeling Technologies, L.L.C.
%
function lorenz
% create the model
m = create_lorenz;

% simulate the model
o = m.simex(100);

% plot the results
createfigure(o.x(:,2),o.y(:,2),o.z(:,2));

end

function m = create_lorenz

% create the Model object
m = Model('lorenz');
m.solver = 'ode45';
m.timeIterator.reltol = 1e-8;
m.timeIterator.abstol = 1e-8;

% define the inputs
sigma = m.input('sigma', 10);
rho = m.input('rho', 28);
beta = m.input('beta', 8/3);

% define the states
x = m.state(0.001);
y = m.state(1);
z = m.state(1.05);

% three differential equations describe the evolution
m.diffequ(x, sigma*(y-x));
m.diffequ(y, x*(rho-z)-y);
m.diffequ(z, x*y - beta*z);

% define three outputs for each of the states
m.output(x);
m.output(y);
m.output(z);

end

function createfigure(X1, Y1, Z1)
%CREATEFIGURE(X1,Y1,Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 16-Sep-2010 16:00:46

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[13.5 18]);
hold(axes1,'all');

% Create plot3
plot3(X1,Y1,Z1);

% Create title
title('Lorenz Attractor');

% Create xlabel
xlabel('x','HorizontalAlignment','right');

% Create ylabel
ylabel('y','HorizontalAlignment','left');

% Create zlabel
zlabel('z');

end