function OptionValue = GARCH_simulation(NumberOfSteps,NumberOfPaths,strike,InterestRate)  
%Determine the value of an Asian option based on GARCH simulation.
%
%[VALUE] = GARCH_SIMULATION(DAYS, PATHS, STRIKE, RATE) determines the
%value of an Asian option over a number of DAYS, with a total number of
%PATHS evaluated.  Strike price is in STRIKE and the risk-free interest rate is in
%RATE.
%
%The function "simulation" calculates the option value by Monte Carlo
%simulation,and draws 5 sample paths of stock price evolution and another
%picture showing the speed of convergence.  We only consider one step every day.

%"summition" and "OptionValue" are both 1*NumberOfPaths vectors.
%"summition(i)" is the sum of i payoffs generated by the first i sample paths. 
%"OptionValue(i)" is the option value given by the first i sample paths.
summition=zeros(1,NumberOfPaths);       
OptionValue = zeros(1,NumberOfPaths);

S0 = 50;                %initial asset price   
r = InterestRate/365.0; %one-period(one-day) risk free interest rate
discount = exp(-r*NumberOfSteps);  

%"tic" and "toc" are used to record the time spent in Monte Carlo
%simulations.
tic;
[S] = GARCH(S0,NumberOfSteps,r);
AvePrice = mean(S);
payoff=max(0,AvePrice-strike);
summition(1)=payoff;
OptionValue(1)=summition(1)*discount;
%plot(1:NumberOfSteps+1,[S0,S]);                    
%hold on;
for i = 2:NumberOfPaths
    [S] = GARCH(S0,NumberOfSteps,r);
    AvePrice = mean(S);
    payoff=max(0,AvePrice-strike);
    summition(i)=summition(i-1)+payoff;
    OptionValue(i)= (summition(i)/i)*discount;
    if i<=6
        plotData(:,i-1) = [S0 S]';                 %Plot 5 sample paths.
    end
end
simulationTime = toc
figure,
plot(plotData)
xlabel('Time');
ylabel('Stock Price');
title('5 sample paths');
hold off;
figure;
plot(1:NumberOfPaths,OptionValue);                     %Plot the convergence of option value as the number of paths increases.
xlabel('Number Of Sample Paths');
ylabel('Asian Option Value');
%set(gca, 'ylim', [4.3, 5]);
title('The convergence of Asion option value as the number of sample paths increases');

fprintf('The Asian Option value after %d simulations is %.4e\n', NumberOfPaths, OptionValue(NumberOfPaths));
fprintf('Completed %d simulations in %0.5g seconds\n', NumberOfPaths, simulationTime)
