# Import subdirectory rules.

# Define local variables.

CLASSES_$(D)    := $(wildcard $(D)/*.m)

TARGETS_$(D)	:= $(CLASSES_$(D))
TARGETS		:= $(TARGETS) $(TARGETS_$(D))
INSTALLS	:= $(INSTALLS) $(D)/install

# Define local rules.

$(D)/install: $(TARGETS_$(D))
	$(INSTALL) -C $^ -d $(INSTALL_PREFIX)
