%% simplot Function Reference
% Displays and visualizes output data from SIMEX simulations
%
% <html>
% <table border=0><tr>
% <td><img src="../images/SIMATRA.png"></td>
% <td><img src="../images/simEngine.png" height=30></td></tr></table>
% </html>
%
%% Description
%     Like the PLOT command, SIMPLOT displays 2D data generated in the
%     native structure output format of SIMEX.  SIMPLOT can also plot
%     vectors and x-y data.
%
%% Usage
%
%     SIMPLOT(XDATA, YDATA, ...)
%     SIMPLOT(XDATA, YDATA, LINEFORMAT, ...)
%     SIMPLOT(MATRIX, ...)
%     SIMPLOT(MATRIX, LINEFORMAT, ...)
%     SIMPLOT(SIMEXOUTPUT, ...)
%     SIMPLOT(SIMEXOUTPUT, LINEFORMAT, ...)
% 
%% Detailed Description:
%     SIMPLOT plots simulation output structures generated by SIMEX
%     in the same manner that the PLOT command will plot X-Y data
%     pairs.  SIMPLOT supports both grouped outputs and multiple
%     outputs per structure.
%
%       XDATA is a 1-D vector of time data
%
%       YDATA is a 1-D vector of value data
%
%       LINEFORMAT is the string format used by PLOT to specify
%       line color and line style
%
%       MATRIX is an N by M matrix where the first column is the
%       time and the remaining M-1 are value vectors plotted
%       against time
%
%       SIMEXOUTPUT is an output structure generated by SIMEX that
%       includes fields that are the same type as MATRIX
%
% Copyright 2009,2010 Simatra Modeling Technologies, L.L.C.
% For more information, please visit http://www.simatratechnologies.com
% For additional help, please email support@simatratechnologies.com%     OUT = SIMEX(DSL, TIME, ...) accepts the following options, all

%% Examples
%
% Run a simulation of the Fitzhugh-Nagumo nerve conduction model.  The
% output of this simulation is:

output = simex([simexamplepath '/FN/fn.dsl'], 100)


%%
% SIMPLOT can individually plot each of the output traces, which are
% time-value pairs

figure
subplot(2,1,1); simplot(output.u); title('u trace')
subplot(2,1,2); simplot(output.w); title('w trace')

%%
% SIMPLOT can also plot multiple traces in one step, either by specifying
% them twice on the command line, or specifying the entire output structure

figure
subplot(2,1,1); simplot(output.u, output.w); title('simplot(output.u, output.w)')
subplot(2,1,2); simplot(output); title('simplot(output)')

%%
% Line styles and colors can be added much like they are used in PLOT

figure
simplot(output.u, 'r+', output.w, 'g*')


%% 
close all

%% See also
% <simex.help.html |simex|>,  <simexamplepath_help.html
% |simexamplepath|>

%% 
% Copyright 2009,2010 Simatra Modeling Technologies, L.L.C.
% For more information, please visit <http://www.simatratechnologies.com>
% For additional help, please email <mailto:support@simatratechnologies.com>
