% PERFORMANCETESTS - this is a clearing house of tests relating to
% performance of the compiler and the resulting simulation engines
%
% Usage:
%  s = CoreFeatureTests - runs all tests
%  s = CoreFeatureTests('-cpu', '-release')
%  s = CoreFeatureTests('-release') - runs only those required for a release
%
function s = PerformanceTests(varargin)

if nargin>0
    target = varargin{1};
else
    target = '-cpu';
end

if nargin<2
   mode = 1;
else
   mode = varargin{2};
end

s = Suite(['Performance Tests ' target]);

%Add each of the performance tests for single execution
%GARCH asset price path model
s.add(Test('Compile GARCH',@ ...
		   ()(simex('models_PerformanceTests/GARCH.dsl', target)), '-withouterror'))
s.add(Test('Simulate GARCH',@ ...
		   ()(simex('models_PerformanceTests/GARCH.dsl', 100, ...
					target)), '-withouterror'))

%Tests with HN model, fwd Euler vs. ode23, and event-based
%vs. continuous ouputs
s.add(Test('Compile HN with fwdEuler (Vm out)',@ ...
		   ()(simex('models_PerformanceTests/hn_fwdEuler.dsl', target)), '-withouterror'))
s.add(Test('Simulate HN with fwdEuler (Vm out)',@ ...
		   ()(simex('models_PerformanceTests/hn_fwdEuler.dsl', 100, target)), '-withouterror'))

s.add(Test('Compile HN with fwdEuler (spikes out)',@ ...
		   ()(simex('models_PerformanceTests/hn_fwdEuler_spikes.dsl', target)), '-withouterror'))
s.add(Test('Simulate HN with fwdEuler (spikes out)',@ ...
		   ()(simex('models_PerformanceTests/hn_fwdEuler_spikes.dsl', 100, ...
					target)), '-withouterror'))

s.add(Test('Compile HN with ode 23 (Vm out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23.dsl', target)), '-withouterror'))
s.add(Test('Simulate HN with ode 23 (Vm out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23.dsl', ...
					100, target)), '-withouterror'))

s.add(Test('Compile HN with ode 23 (spikes out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23_spikes.dsl', target)), '-withouterror'))
s.add(Test('Simulate HN with ode 23 (spikes out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23_spikes.dsl', ...
					100, target)), '-withouterror'))

%Performance tests with GPE network model
s.add(Test('Compile GPE network with ode 23',@ ...
		   ()(simex('models_PerformanceTests/network_ode23.dsl', target)), '-withouterror'))
s.add(Test('Simulate GPE network with ode 23',@ ...
		   ()(simex('models_PerformanceTests/network_ode23.dsl', ...
					1000, target)), '-withouterror'))

%Performance tests with 5 and 10 segment MRG model
s.add(Test('Compile Axon5',@ ...
		   ()(simex('models_PerformanceTests/axon_5segment.dsl', target)), '-withouterror'))
s.add(Test('Simulate Axon5',@ ...
		   ()(simex('models_PerformanceTests/axon_5segment.dsl', ...
					100, target)), '-withouterror'))
s.add(Test('Compile Axon10',@ ...
		   ()(simex('models_PerformanceTests/axon_10segment.dsl', target)), '-withouterror'))
s.add(Test('Simulate Axon10',@ ...
		   ()(simex('models_PerformanceTests/axon_10segment.dsl', ...
					100, target)), '-withouterror'))

%Add tests for multiple execution
GARCH_parameters.S0 = num2cell(100*ones(1,1000));
s.add(Test('Compile GARCH',@ ...
		   ()(simex('models_PerformanceTests/GARCH.dsl', GARCH_parameters, ...
					target)), '-withouterror'))
s.add(Test('Simulate GARCH',@ ...
		   ()(simex('models_PerformanceTests/GARCH.dsl', 100, GARCH_parameters, ...
					target)), '-withouterror'))


hn_parameters.gleak = num2cell(10:.1:20);
s.add(Test('Compile 101 HNs with ode 23 (Vm out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23.dsl', hn_parameters, target)), '-withouterror'))
s.add(Test('Simulate 101 HNs with ode 23 (Vm out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23.dsl', ...
					100, hn_parameters, target)), '-withouterror'))
s.add(Test('Compile 101 HNs with ode 23 (spikes out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23_spikes.dsl', ...
					hn_parameters, target)), '-withouterror'))
s.add(Test('Simulate 101 HNs with ode 23 (spikes out)',@ ...
		   ()(simex('models_PerformanceTests/hn_ode23_spikes.dsl', ...
					100, hn_parameters, target)), '-withouterror'))
end



