function s = SubModelTests(varargin)
%SUBMODELTESTS Tests the basic features of submodels
%   Detailed explanation goes here
%
% Usage:
%  s = SubModelTests - runs all tests
%  s = SubModelTests('-release') - runs only those required for a release
%
INTERNAL = 0; RELEASE = 1;

if nargin == 0
  target = '-cpu';
  mode = RELEASE;
elseif nargin == 1
  target = varargin{1};
  mode = RELEASE;
else
  target = varargin{1};
  mode = varargin{2};
end

s = Suite(['Sub-model Feature Tests ' target]);
s.add(BasicSubModelTests(mode, target));
s.add(HierarchySubModelTests(mode, target));
s.add(AlgebraicSubModelTests(target));
s.add(OrderingTests(target));
s.add(IteratorSubModelTests(target));
s.add(FlattenSubModelTests(target));

end

function s = BasicSubModelTests(mode, target)

s = Suite(['Basic Sub-Model Tests ' target]);

s.add(Test('BasicSubModelTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest1.dsl'], 10,target)), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));
s.add(Test('SubModelInputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest2.dsl'], 10,target)), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));
s.add(Test('DuplicateSubModelInputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest3.dsl'], 10,target)), '-equal', ...
           struct('y', [0:10; 0:2:20; 0:10; 0:3:30]')));
s.add(Test('DuplicateSubModelToOutputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest4.dsl'], 10,target)), '-equal', ...
           struct('y', [0:10; 0:2:20; 0:10; 0:3:30]')));
s.add(Test('SubModelDefaultInputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest5.dsl'], 10,target)), '-equal', ...
           struct('y', [0:10; 0:2:20; 0:2:20; 0:10]')));

INTERNAL = 0; RELEASE = 1;

% this is related to init values driven by inputs
s.add(Test('SubModelInputToInitTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest6.dsl'], 10,target)), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));

end

function s = HierarchySubModelTests(mode, target)

s = Suite(['Hierarchy Sub-Model Tests ' target]);

s.add(Test('DeepHierarchy', ...
            @()(simex(['models_FeatureTests/HierarchySubModelTest1.dsl'], 10,target)), ...
            '-equal', struct('y', [0:10; 0:3:30; 0:10]')));

s.add(Test('DeepHybridHierarchy', ...
            @()(simex(['models_FeatureTests/HierarchySubModelTest2.dsl'], 10,target)), ...
            '-equal', struct('y', [0:10; 0:3:30; 0:10; 0:4:40]')));

s.add(Test('DeeperHierarchy', ...
            @()(simex(['models_FeatureTests/HierarchySubModelTest3.dsl'], 10,target)), ...
            '-equal', struct('y', [0:10; 0:3:30; 0:8:80; 0:10]')));

end

function s = AlgebraicSubModelTests(target)
s = Suite(['Algebraic Sub-Model Tests ' target]);

s.add(Test('BasicAlgebraicSubModelTest', ...
            @()(simex(['models_FeatureTests/AlgebraicSubModelTest1.dsl'], 10, target)), ...
            '-equal', struct('y', [0:10; 0:10; (0:10).^2]')));
s.add(Test('MultipleIterators', ...
            @()(simex(['models_FeatureTests/AlgebraicSubModelTest2.dsl'], 10, target)), ...
            '-equal', struct('y', [0:10; 0:10; (0:10).^2.*3; (0:10).^2.*3]')));
s.add(Test('IteratorOfInput', ...
            @()(simex(['models_FeatureTests/AlgebraicSubModelTest4.dsl'], 10, target)), ...
            '-equal', struct('y', [0:10; (0:10).^2]', ...
                             'z', [0:10; 0:10]')));
end

function s = OrderingTests(target)

s = Suite(['Ordering Tests ' target]);

s.add(Test('CascadedModelTest', ...
            @()(simex(['models_FeatureTests/OrderingTest1.dsl'], 10,target)), ...
            '-equal', struct('y', [0:10; 0:10;cumsum([0 0:9])]')));
s.add(Test('FlippedCascadedModelTest', @()(simex(['models_FeatureTests/' ...
                    'OrderingTest2.dsl'], 10,target)), '-equal', ...
            struct('y', [0:10; cumsum([0 0:9]); 0:10]')));
s.add(Test('InterconnectedModelTest1', @()(simex(['models_FeatureTests/' ...
                    'OrderingTest3.dsl'], 10,target)), '-equal', ...
            struct('y', [0:10; zeros(1,11); zeros(1,11)]')));
s.add(Test('InterconnectedModelTest2', @()(simex(['models_FeatureTests/' ...
                    'OrderingTest4.dsl'], 10,target)), '-equal', ...
            struct('y', [0:10; 2.^(0:10); 2.^(0:10)]')));
end

function s = IteratorSubModelTests(target)

s = Suite(['Iterator Sub Model Tests ' target]);

s.add(Test('IteratorOnIntermediate', ...
            @()(simex(['models_FeatureTests/IteratorSubModelTest1.dsl'], 10,target)), ...
            '-equal', struct('y', [0:10; 0:10; [0 0:9]]')));
s.add(Test('IteratorOnOutput', ...
            @()(simex(['models_FeatureTests/IteratorSubModelTest2.dsl'], 10,target)), ...
            '-equal', struct('y', [0:10; 0:10; [0 0:9]]')));
s.add(Test('IteratorOnInput', ...
            @()(simex(['models_FeatureTests/IteratorSubModelTest3.dsl'], 10,target)), ...
            '-equal', struct('y', [0:10; 0:10; [0 0:9]]')));

end

function s = FlattenSubModelTests(target)

s = Suite(['Flatten Sub Tests ' target]);

s.add(Test('FlattenBasicSubModelTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest1.dsl'], 10,target, '-flatten')), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));
s.add(Test('FlattenSubModelInputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest2.dsl'], 10,target, '-flatten')), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));
s.add(Test('FlattenDuplicateSubModelInputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest3.dsl'], 10,target, '-flatten')), '-equal', ...
           struct('y', [0:10; 0:2:20; 0:10; 0:3:30]')));
s.add(Test('FlattenDuplicateSubModelToOutputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest4.dsl'], 10,target, '-flatten')), '-equal', ...
           struct('y', [0:10; 0:2:20; 0:10; 0:3:30]')));
s.add(Test('FlattenSubModelDefaultInputTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest5.dsl'], 10,target, '-flatten')), '-equal', ...
           struct('y', [0:10; 0:2:20; 0:2:20; 0:10]')));

% this is related to init values driven by inputs
s.add(Test('FlattenSubModelInputToInitTest', @()(simex(['models_FeatureTests/' ...
                    'SubModelTest6.dsl'], 10,target, '-flatten')), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));

s.add(Test('FlattenIteratorInSubModel', @()(simex(['models_FeatureTests/' ...
                    'FlattenSubModelTest1.dsl'], 10,target, '-flatten')), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));
s.add(Test('IteratorInOutputIntermediate', @()(simex(['models_FeatureTests/' ...
                    'FlattenSubModelTest2.dsl'], 10,target, '-flatten')), '-equal', struct('y', [0:10; 0:2:20; 0:10]')));

end


