# Define local variables.

CLASSES_$(D)	:= $(wildcard $(D)/*.m)

TARGETS_$(D)	:= $(CLASSES_$(D))
TARGETS		:= $(TARGETS) $(TARGETS_$(D))
INSTALLS	:= $(INSTALLS) $(D)/installs

# Import subsystem rules.

# Define local rules.

$(D)/installs: $(TARGETS_$(D))
	$(INSTALL) -C $^ -d $(INSTALL_PREFIX)