# Define local variables.

CLASSES_$(D)	:= $(wildcard $(D)/*.m)

TARGETS_$(D)	:= $(CLASSES_$(D))
TARGETS		:= $(TARGETS) $(TARGETS_$(D))
INSTALL_ROOT    := $(INSTALL_ROOT) $(TARGETS_$(D))
CLEAN		:= $(CLEAN) $(TARGETS_$(D))

# Import subsystem rules.

# Define local rules.
