println (||.match "")
println (||.match "nope")
println (|*|.match "")
println (|*|.match "hey there mr mofongo")
println (|?|.match "a")
println (|?|.match "")
println (|?|.match "toolong")
println (|test?this*|.match "test this!!!!")
println (|test?this*|.match "test this")
println (|test?this*|.match "test1this")
println (|test?this*|.match "testthis")
println (|this totally doesn't match|.match "not at all")
println (|hey***you|.match "heyyou")
println (|hey***you|.match "heylksjflksjdfksdjflkjflksjfklsdjklsdjflsjyou")
println (|fore?score?|.match "fore score!")
