/* Copyright (C) 2010 by Simatra Modeling Technologies, L.L.C. */

#include <stdlib.h>
#include <string.h>
#include <errno.h>

/* The header should be generated by MLton.
 * It shall declare MLton's own data types
 * as well as the signatures of all
 * exported functions (e.g. those use to
 * allocate memory for arrays.) */
#include "ffi-exports.h"

enum status {
  DeviceProps_Success,
  DeviceProps_EmulationOnly,
  DeviceProps_NoDevices,
  DeviceProps_UnknownError,
  DeviceProps_NoCudaRuntime
};

void cuda_devicePropsError (void)
    {
    char *message = devicePropsError();
    make_the_string(strlen(message), message);
    }

Int32_t cuda_getDeviceProps (void)
    {
    int ndevices, sort;
    char *props;

    int status = getDeviceProps(&ndevices, &props);
    if (DeviceProps_Success != status)
	return status;

    for (sort = 0; sort < ndevices; sort++) 
	{
	int length = strlen(props);
	push_a_string(length, props);
	props += 1 + length;
	}

    return status;
    }
